version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - "/src/node_modules"
          key: "npm-Packages"
      - run:
          name: "run build"
          command: npm run lint

  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-Packages"
      - run:
          name: "run test"
          command: npm run test

  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-Packages"
      - run:
          name: "run security test"
          command: npm audit

workflows:
  ci-pipline-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
